forge flatten contracts/L2PValidatorSet.sol -o contracts/flattened/L2PValidatorSet.sol
forge flatten contracts/GovHub.sol -o contracts/flattened/GovHub.sol
forge flatten contracts/SlashIndicator.sol -o contracts/flattened/SlashIndicator.sol
forge flatten contracts/SystemReward.sol -o contracts/flattened/SystemReward.sol
forge flatten contracts/StakeHub.sol -o contracts/flattened/StakeHub.sol
forge flatten contracts/StakeCredit.sol -o contracts/flattened/StakeCredit.sol
forge flatten contracts/L2PGovernor.sol -o contracts/flattened/L2PGovernor.sol
forge flatten contracts/GovToken.sol -o contracts/flattened/GovToken.sol
forge flatten contracts/L2PTimelock.sol -o contracts/flattened/L2PTimelock.sol
forge flatten contracts/ens/ENSRegistry.sol -o contracts/flattened/ens/ENSRegistry.sol